### ISSUE TITLE
Update README with setup instruction

### ISSUE THREAD

**Issue by andmos** [geirsagberg/github-deploy-center#4]
It would be great with a README that describes the setup process, both for hosting the site and a description of what workflows that needs to exist for `github-deploy-center` to be used for a repo 🙏

**Comment by geirsagberg** [comment]
@andmos I have updated the README a bit, could you take a look and let me know if things are clear, alternatively suggest improvements? :)

**Comment by andmos** [comment]
Just what I had in mind. Looks good! I'm going to use this project quite soon!
